name: Run Kalua Workflow
on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/30 * * * *'

jobs:
  run_Spike_workflow:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        cpu: [4]
    
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Kalua binaries
        run: |
          chmod +x Kalua

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install required packages
        run: |
          pip install pymongo python-telegram-bot pyTelegramBotAPI certifi

      - name: Run Kalua.py
        run: python3 Kalua.py 
